use batcherbird_core::detection::DetectionConfig;
use batcherbird_core::export::{
    read_wav_metadata, AudioFormat, BatchExportConfig, BatchExporter, ExportConfig, SampleExporter,
};
use batcherbird_core::sampler::Sample;
use std::time::{Duration, SystemTime};

#[test]
fn test_sfz_export() {
    // Create test samples
    let test_samples = vec![
        Sample {
            note: 60, // C4
            velocity: 64,
            audio_data: vec![0.5, 0.3, 0.1, 0.0, -0.1, -0.3, -0.5],
            sample_rate: 44100,
            channels: 1,
            recorded_at: SystemTime::now(),
            midi_timing: Duration::from_millis(100),
            audio_timing: Duration::from_millis(2000),
        },
        Sample {
            note: 60, // C4
            velocity: 127,
            audio_data: vec![0.8, 0.6, 0.2, 0.0, -0.2, -0.6, -0.8],
            sample_rate: 44100,
            channels: 1,
            recorded_at: SystemTime::now(),
            midi_timing: Duration::from_millis(100),
            audio_timing: Duration::from_millis(2000),
        },
    ];

    // Create temp directory for test
    let temp_dir = std::env::temp_dir().join("batcherbird_test_sfz");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let config = ExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "TestInstrument_{note_name}_{note}_{velocity}.wav".to_string(),
        sample_format: AudioFormat::SFZ,
        normalize: false,
        fade_in_ms: 0.0,
        fade_out_ms: 0.0,
        apply_detection: false,
        auto_loop: false,
        detection_config: DetectionConfig::default(),
        creator_name: Some("Test User".to_string()),
        instrument_description: Some("Test SFZ instrument".to_string()),
        embed_metadata: true,
    };

    let exporter = SampleExporter::new(config).unwrap();
    let files = exporter.export_samples(&test_samples).unwrap();

    // Should have 2 WAV files + 1 SFZ file
    assert_eq!(files.len(), 3);

    // Find and verify SFZ file
    let sfz_file = files
        .iter()
        .find(|f| f.extension().is_some_and(|ext| ext == "sfz"))
        .unwrap();
    let sfz_content = std::fs::read_to_string(sfz_file).unwrap();

    assert!(sfz_content.contains("Generated by Batcherbird"));
    assert!(sfz_content.contains("Creator: Test User"));
    assert!(sfz_content.contains("<group>"));
    assert!(sfz_content.contains("lovel="));
    assert!(sfz_content.contains("hivel="));
    assert!(sfz_content.contains("<region>"));
    assert!(sfz_content.contains("sample="));
    assert!(sfz_content.contains("key=60"));

    // Cleanup
    std::fs::remove_dir_all(&temp_dir).ok();
}

#[test]
fn test_decent_sampler_export() {
    let sine_wave: Vec<f32> = (0..44100)
        .map(|i| (2.0 * std::f32::consts::PI * 440.0 * i as f32 / 44100.0).sin() * 0.5)
        .collect();

    // Create test samples
    let test_samples = vec![
        Sample {
            note: 64, // E4
            velocity: 64,
            audio_data: sine_wave.clone(),
            sample_rate: 44100,
            channels: 1,
            recorded_at: SystemTime::now(),
            midi_timing: Duration::from_millis(100),
            audio_timing: Duration::from_millis(2000),
        },
        Sample {
            note: 64, // E4
            velocity: 127,
            audio_data: sine_wave,
            sample_rate: 44100,
            channels: 1,
            recorded_at: SystemTime::now(),
            midi_timing: Duration::from_millis(100),
            audio_timing: Duration::from_millis(2000),
        },
    ];

    // Create temp directory for test
    let temp_dir = std::env::temp_dir().join("batcherbird_test_dspreset");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let config = ExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "TestInstrument_{note_name}_{note}_{velocity}.wav".to_string(),
        sample_format: AudioFormat::DecentSampler,
        normalize: false,
        fade_in_ms: 0.0,
        fade_out_ms: 0.0,
        apply_detection: true,
        auto_loop: true,
        detection_config: DetectionConfig::default(),
        creator_name: Some("Test User".to_string()),
        instrument_description: Some("Test Decent Sampler instrument".to_string()),
        embed_metadata: true,
    };

    let exporter = SampleExporter::new(config).unwrap();
    let files = exporter.export_samples(&test_samples).unwrap();

    // Should have 2 WAV files + 1 .dspreset file
    assert_eq!(files.len(), 3);

    // Find and verify .dspreset file
    let dspreset_file = files
        .iter()
        .find(|f| f.extension().is_some_and(|ext| ext == "dspreset"))
        .unwrap();
    let dspreset_content = std::fs::read_to_string(dspreset_file).unwrap();

    assert!(dspreset_content.contains("Generated by Batcherbird"));
    assert!(dspreset_content.contains("Test User"));
    assert!(dspreset_content.contains("<DecentSampler"));
    assert!(dspreset_content.contains("<group loVel="));
    assert!(dspreset_content.contains("<sample"));
    assert!(dspreset_content.contains("path="));
    assert!(dspreset_content.contains("loNote=\"64\""));
    assert!(dspreset_content.contains("loopEnabled=\"true\""));
    assert!(dspreset_content.contains("loopCrossfade="));

    // Cleanup
    std::fs::remove_dir_all(&temp_dir).ok();
}

#[test]
fn test_sfz_export_with_loop_crossfade() {
    let sine_wave: Vec<f32> = (0..44100)
        .map(|i| (2.0 * std::f32::consts::PI * 440.0 * i as f32 / 44100.0).sin() * 0.5)
        .collect();

    let test_samples = vec![Sample {
        note: 60,
        velocity: 100,
        audio_data: sine_wave,
        sample_rate: 44100,
        channels: 1,
        recorded_at: SystemTime::now(),
        midi_timing: Duration::from_millis(100),
        audio_timing: Duration::from_millis(2000),
    }];

    let temp_dir = std::env::temp_dir().join("batcherbird_test_sfz_loop");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let config = ExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "Test_{note_name}_{note}_{velocity}.wav".to_string(),
        sample_format: AudioFormat::SFZ,
        normalize: false,
        fade_in_ms: 0.0,
        fade_out_ms: 0.0,
        apply_detection: true,
        auto_loop: true,
        detection_config: DetectionConfig::default(),
        creator_name: Some("Test User".to_string()),
        instrument_description: Some("Test SFZ Loop instrument".to_string()),
        embed_metadata: true,
    };

    let exporter = SampleExporter::new(config).unwrap();
    let files = exporter.export_samples(&test_samples).unwrap();

    let sfz_file = files
        .iter()
        .find(|f| f.extension().is_some_and(|ext| ext == "sfz"))
        .unwrap();
    let sfz_content = std::fs::read_to_string(sfz_file).unwrap();

    assert!(sfz_content.contains("loop_mode=loop_continuous"));
    assert!(sfz_content.contains("loop_start="));
    assert!(sfz_content.contains("loop_end="));
    assert!(sfz_content.contains("loop_crossfade="));

    // Cleanup
    std::fs::remove_dir_all(&temp_dir).ok();
}

#[test]
fn test_riff_metadata_embedding_roundtrip() {
    let sine_wave: Vec<f32> = (0..44100)
        .map(|i| (2.0 * std::f32::consts::PI * 440.0 * i as f32 / 44100.0).sin() * 0.5)
        .collect();

    let sample = Sample {
        note: 69, // A4
        velocity: 110,
        audio_data: sine_wave,
        sample_rate: 44100,
        channels: 1,
        recorded_at: SystemTime::now(),
        midi_timing: Duration::from_millis(100),
        audio_timing: Duration::from_millis(1000),
    };

    let temp_dir = std::env::temp_dir().join("batcherbird_test_riff_metadata");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let config = ExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "Meta_{note_name}_{note}_{velocity}.wav".to_string(),
        sample_format: AudioFormat::Wav24Bit,
        normalize: false,
        fade_in_ms: 0.0,
        fade_out_ms: 0.0,
        apply_detection: true,
        auto_loop: true,
        detection_config: DetectionConfig::default(),
        creator_name: Some("Batcherbird Studio".to_string()),
        instrument_description: Some("Custom Prophet-5 Lead".to_string()),
        embed_metadata: true,
    };

    let exporter = SampleExporter::new(config).unwrap();
    let wav_path = exporter.export_sample(&sample).unwrap();

    // Verify file exists
    assert!(wav_path.exists());

    // Verify hound can read audio data without any corruption
    let mut reader = hound::WavReader::open(&wav_path).unwrap();
    let spec = reader.spec();
    assert_eq!(spec.sample_rate, 44100);
    assert_eq!(spec.channels, 1);
    assert_eq!(spec.bits_per_sample, 24);
    let sample_count = reader.samples::<i32>().count();
    assert_eq!(sample_count, 44100);

    // Read and verify RIFF chunk metadata
    let meta = read_wav_metadata(&wav_path).unwrap();

    // smpl chunk
    assert_eq!(meta.midi_unity_note, Some(69));
    assert_eq!(meta.sample_period_ns, Some(22676)); // 1_000_000_000 / 44100 = 22675.7 -> 22676
    assert!(meta.loop_points.is_some());

    // bext chunk
    assert_eq!(meta.bext_originator.as_deref(), Some("Batcherbird Studio"));
    assert_eq!(
        meta.bext_description.as_deref(),
        Some("Custom Prophet-5 Lead")
    );
    assert!(meta.bext_origination_date.is_some());
    assert!(meta.bext_origination_time.is_some());

    // INFO chunk
    assert_eq!(meta.info_title.as_deref(), Some("A4 (Note 69)"));
    assert_eq!(meta.info_artist.as_deref(), Some("Batcherbird Studio"));
    assert_eq!(meta.info_software.as_deref(), Some("Batcherbird"));
    assert!(meta.info_comment.unwrap().contains("Velocity: 110"));

    // Cleanup
    std::fs::remove_dir_all(&temp_dir).ok();
}

#[test]
fn test_simultaneous_ds_and_sfz_integration() {
    let sine_wave: Vec<f32> = (0..22050)
        .map(|i| (2.0 * std::f32::consts::PI * 440.0 * i as f32 / 44100.0).sin() * 0.5)
        .collect();

    let sample = Sample {
        note: 60,
        velocity: 100,
        audio_data: sine_wave,
        sample_rate: 44100,
        channels: 1,
        recorded_at: SystemTime::now(),
        midi_timing: Duration::from_millis(50),
        audio_timing: Duration::from_millis(500),
    };

    let temp_dir = std::env::temp_dir().join("batcherbird_test_simul_integration");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let config = ExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "Patch_{note_name}_{note}_{velocity}.wav".to_string(),
        sample_format: AudioFormat::DecentSamplerAndSfz,
        normalize: false,
        fade_in_ms: 0.0,
        fade_out_ms: 0.0,
        apply_detection: false,
        auto_loop: false,
        detection_config: DetectionConfig::default(),
        creator_name: Some("Sound Designer".to_string()),
        instrument_description: Some("Hybrid Pad".to_string()),
        embed_metadata: true,
    };

    let exporter = SampleExporter::new(config).unwrap();
    let exported = exporter.export_samples(&[sample]).unwrap();

    // 1 WAV file + 1 .dspreset + 1 .sfz = 3 files
    assert_eq!(exported.len(), 3);

    let dspreset_path = temp_dir.join("Patch.dspreset");
    let sfz_path = temp_dir.join("Patch.sfz");
    let wav_path = temp_dir.join("Patch_C4_60_vel100.wav");

    assert!(dspreset_path.exists());
    assert!(sfz_path.exists());
    assert!(wav_path.exists());

    // Both presets should reference the exact same relative WAV filename
    let ds_xml = std::fs::read_to_string(&dspreset_path).unwrap();
    let sfz_txt = std::fs::read_to_string(&sfz_path).unwrap();

    assert!(ds_xml.contains("Patch_C4_60_vel100.wav"));
    assert!(sfz_txt.contains("Patch_C4_60_vel100.wav"));

    std::fs::remove_dir_all(&temp_dir).ok();
}

#[test]
fn test_batch_exporter_pipeline_integration() {
    let sample = Sample {
        note: 72,
        velocity: 120,
        audio_data: vec![0.1; 1000],
        sample_rate: 44100,
        channels: 1,
        recorded_at: SystemTime::now(),
        midi_timing: Duration::from_millis(50),
        audio_timing: Duration::from_millis(500),
    };

    let temp_dir = std::env::temp_dir().join("batcherbird_test_batch_pipeline");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let batch_cfg = BatchExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "Test_{note_name}_{note}_{velocity}.wav".to_string(),
        formats: vec![
            AudioFormat::DecentSampler,
            AudioFormat::SFZ,
            AudioFormat::Wav16Bit,
        ],
        organize_subdirectories: true,
        ..Default::default()
    };

    let batch_exp = BatchExporter::new(batch_cfg).unwrap();
    let res = batch_exp.export_samples(&[sample]).unwrap();

    assert_eq!(res.files_by_format.len(), 3);
    assert!(temp_dir.join("DecentSampler/Test.dspreset").exists());
    assert!(temp_dir.join("SFZ/Test.sfz").exists());
    assert!(temp_dir.join("WAV_16Bit/Test_C5_72_vel120.wav").exists());

    std::fs::remove_dir_all(&temp_dir).ok();
}

fn fixture_sample(note: u8, velocity: u8, channels: u16) -> Sample {
    Sample {
        note,
        velocity,
        channels,
        sample_rate: 1000,
        audio_data: (0..1000)
            .flat_map(|frame| {
                let value = if (200..800).contains(&frame) {
                    (std::f32::consts::TAU * frame as f32 / 20.0).sin() * 0.5
                } else {
                    0.0
                };
                (0..channels).map(move |channel| if channel == 0 { value } else { -value })
            })
            .collect(),
        recorded_at: SystemTime::now(),
        midi_timing: Duration::ZERO,
        audio_timing: Duration::from_secs(1),
    }
}

#[test]
fn sparse_note_and_velocity_zones_cover_once_and_paths_resolve() {
    let temp = std::env::temp_dir().join("batcherbird_zones_regression");
    let samples: Vec<_> = [30, 90, 127]
        .into_iter()
        .flat_map(|velocity| {
            [60, 64, 72]
                .into_iter()
                .map(move |note| fixture_sample(note, velocity, 1))
        })
        .collect();
    let exporter = SampleExporter::new(ExportConfig {
        output_directory: temp.clone(),
        sample_format: AudioFormat::DecentSamplerAndSfz,
        apply_detection: false,
        fade_out_ms: 0.0,
        ..Default::default()
    })
    .unwrap();
    let files = exporter.export_samples(&samples).unwrap();
    let sfz = std::fs::read_to_string(
        files
            .iter()
            .find(|p| p.extension().unwrap() == "sfz")
            .unwrap(),
    )
    .unwrap();
    let xml = std::fs::read_to_string(
        files
            .iter()
            .find(|p| p.extension().unwrap() == "dspreset")
            .unwrap(),
    )
    .unwrap();
    let number = |text: &str, key: &str| -> u8 {
        text.split(&format!("{}=", key))
            .nth(1)
            .unwrap()
            .split_whitespace()
            .next()
            .unwrap()
            .parse()
            .unwrap()
    };
    let mut regions = Vec::new();
    for group in sfz.split("<group>").skip(1) {
        let low_velocity = number(group, "lovel");
        let high_velocity = number(group, "hivel");
        for region in group.split("<region>").skip(1) {
            regions.push((
                number(region, "lokey"),
                number(region, "hikey"),
                low_velocity,
                high_velocity,
            ));
            let filename = region
                .split("sample=")
                .nth(1)
                .unwrap()
                .lines()
                .next()
                .unwrap();
            assert!(temp.join(filename).is_file());
        }
    }
    for key in 60..=72 {
        for velocity in 1..=127 {
            assert_eq!(
                regions
                    .iter()
                    .filter(|&&(lo, hi, lv, hv)| key >= lo
                        && key <= hi
                        && velocity >= lv
                        && velocity <= hv)
                    .count(),
                1,
                "key {key}, velocity {velocity}"
            );
        }
    }
    for (lo, hi, lv, hv) in regions {
        assert!(xml.contains(&format!("loNote=\"{lo}\" hiNote=\"{hi}\"")));
        assert!(xml.contains(&format!("loVel=\"{lv}\" hiVel=\"{hv}\"")));
    }
    assert!(sfz.contains("default_path=./"));
    assert!(!sfz.contains("loop_mode="));
    assert!(!xml.contains("loopEnabled="));
    std::fs::remove_dir_all(temp).unwrap();
}

#[test]
fn stereo_trimmed_wav_and_presets_share_frame_loop_coordinates() {
    let temp = std::env::temp_dir().join("batcherbird_stereo_loop_regression");
    let sample = fixture_sample(60, 100, 2);
    let exporter = SampleExporter::new(ExportConfig {
        output_directory: temp.clone(),
        sample_format: AudioFormat::DecentSamplerAndSfz,
        auto_loop: true,
        fade_out_ms: 0.0,
        detection_config: DetectionConfig {
            pre_trigger_ms: 0.0,
            post_trigger_ms: 0.0,
            confirmation_windows: 1,
            ..Default::default()
        },
        ..Default::default()
    })
    .unwrap();
    let files = exporter.export_samples(&[sample]).unwrap();
    let wav = files
        .iter()
        .find(|p| p.extension().unwrap() == "wav")
        .unwrap();
    let reader = hound::WavReader::open(wav).unwrap();
    let frames = reader.duration();
    assert!(frames < 1000 && frames > 500, "trimmed frames: {frames}");
    let (start, end) = read_wav_metadata(wav)
        .unwrap()
        .loop_points
        .expect("periodic stereo has a loop");
    assert!(start < end && end < frames);
    let sfz = std::fs::read_to_string(
        files
            .iter()
            .find(|p| p.extension().unwrap() == "sfz")
            .unwrap(),
    )
    .unwrap();
    let xml = std::fs::read_to_string(
        files
            .iter()
            .find(|p| p.extension().unwrap() == "dspreset")
            .unwrap(),
    )
    .unwrap();
    assert!(sfz.contains(&format!("loop_start={start}\nloop_end={end}\n")));
    assert!(xml.contains(&format!("loopStart=\"{start}\" loopEnd=\"{end}\"")));
    // DecentSampler expresses crossfade length in frames; SFZ uses seconds.
    assert!(xml.contains("loopCrossfade=\"10\""));
    assert!(sfz.contains("loop_crossfade=0.010"));
    std::fs::remove_dir_all(temp).unwrap();
}

#[test]
fn stereo_fades_keep_channels_paired_and_use_frame_duration() {
    let temp = std::env::temp_dir().join("batcherbird_stereo_fade_regression");
    let mut sample = fixture_sample(60, 100, 2);
    sample.audio_data = (0..20).flat_map(|_| [0.5, -0.5]).collect();
    let exporter = SampleExporter::new(ExportConfig {
        output_directory: temp.clone(),
        sample_format: AudioFormat::Wav32BitFloat,
        apply_detection: false,
        fade_in_ms: 10.0,
        fade_out_ms: 10.0,
        ..Default::default()
    })
    .unwrap();
    let path = exporter.export_sample(&sample).unwrap();
    let audio: Vec<f32> = hound::WavReader::open(path)
        .unwrap()
        .samples::<f32>()
        .map(Result::unwrap)
        .collect();
    for pair in audio.as_chunks::<2>().0.iter() {
        assert_eq!(pair[0], -pair[1]);
    }
    assert_eq!(audio[0], 0.0);
    assert_eq!(audio[38], 0.0);
    assert_eq!(audio[18], 0.5);
    assert_eq!(audio[20], 0.5);
    std::fs::remove_dir_all(temp).unwrap();
}

#[test]
fn shared_batch_preserves_preset_wavs_when_exporting_alternate_depths() {
    let temp = std::env::temp_dir().join("batcherbird_depth_regression");
    let exporter = BatchExporter::new(BatchExportConfig {
        output_directory: temp.clone(),
        formats: vec![
            AudioFormat::DecentSampler,
            AudioFormat::SFZ,
            AudioFormat::Wav16Bit,
            AudioFormat::Wav32BitFloat,
        ],
        organize_subdirectories: false,
        apply_detection: false,
        ..Default::default()
    })
    .unwrap();
    let result = exporter
        .export_samples(&[fixture_sample(60, 100, 1)])
        .unwrap();
    let paths: Vec<_> = result
        .all_files
        .iter()
        .filter(|p| p.extension().unwrap() == "wav")
        .collect();
    assert_eq!(paths.len(), 3);
    let wav = "C4_60_vel100.wav";
    assert_eq!(
        hound::WavReader::open(temp.join(wav))
            .unwrap()
            .spec()
            .bits_per_sample,
        24
    );
    assert_eq!(
        hound::WavReader::open(temp.join("WAV_16Bit").join(wav))
            .unwrap()
            .spec()
            .bits_per_sample,
        16
    );
    assert_eq!(
        hound::WavReader::open(temp.join("WAV_32BitFloat").join(wav))
            .unwrap()
            .spec()
            .bits_per_sample,
        32
    );
    std::fs::remove_dir_all(temp).unwrap();
}

#[test]
fn duplicate_filename_pattern_rejected_before_writing_audio() {
    let temp = std::env::temp_dir().join("batcherbird_duplicate_name_regression");
    let exporter = SampleExporter::new(ExportConfig {
        output_directory: temp.clone(),
        naming_pattern: "same.wav".into(),
        ..Default::default()
    })
    .unwrap();
    assert!(exporter
        .export_samples(&[fixture_sample(60, 100, 1), fixture_sample(64, 100, 1)])
        .is_err());
    assert!(!temp.join("same.wav").exists());
    std::fs::remove_dir_all(temp).unwrap();
}
