use batcherbird_core::detection::DetectionConfig;
use batcherbird_core::export::{
    read_wav_metadata, AudioFormat, BatchExportConfig, BatchExporter, ExportConfig, SampleExporter,
};
use batcherbird_core::sampler::Sample;
use std::time::{Duration, SystemTime};

#[test]
fn test_sfz_export() {
    // Create test samples
    let test_samples = vec![
        Sample {
            note: 60, // C4
            velocity: 64,
            audio_data: vec![0.5, 0.3, 0.1, 0.0, -0.1, -0.3, -0.5],
            sample_rate: 44100,
            channels: 1,
            recorded_at: SystemTime::now(),
            midi_timing: Duration::from_millis(100),
            audio_timing: Duration::from_millis(2000),
        },
        Sample {
            note: 60, // C4
            velocity: 127,
            audio_data: vec![0.8, 0.6, 0.2, 0.0, -0.2, -0.6, -0.8],
            sample_rate: 44100,
            channels: 1,
            recorded_at: SystemTime::now(),
            midi_timing: Duration::from_millis(100),
            audio_timing: Duration::from_millis(2000),
        },
    ];

    // Create temp directory for test
    let temp_dir = std::env::temp_dir().join("batcherbird_test_sfz");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let config = ExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "TestInstrument_{note_name}_{note}_{velocity}.wav".to_string(),
        sample_format: AudioFormat::SFZ,
        normalize: false,
        fade_in_ms: 0.0,
        fade_out_ms: 0.0,
        apply_detection: false,
        detection_config: DetectionConfig::default(),
        creator_name: Some("Test User".to_string()),
        instrument_description: Some("Test SFZ instrument".to_string()),
        embed_metadata: true,
    };

    let exporter = SampleExporter::new(config).unwrap();
    let files = exporter.export_samples(&test_samples).unwrap();

    // Should have 2 WAV files + 1 SFZ file
    assert_eq!(files.len(), 3);

    // Find and verify SFZ file
    let sfz_file = files
        .iter()
        .find(|f| f.extension().is_some_and(|ext| ext == "sfz"))
        .unwrap();
    let sfz_content = std::fs::read_to_string(sfz_file).unwrap();

    assert!(sfz_content.contains("Generated by Batcherbird"));
    assert!(sfz_content.contains("Creator: Test User"));
    assert!(sfz_content.contains("<group>"));
    assert!(sfz_content.contains("lovel="));
    assert!(sfz_content.contains("hivel="));
    assert!(sfz_content.contains("<region>"));
    assert!(sfz_content.contains("sample="));
    assert!(sfz_content.contains("key=60"));

    // Cleanup
    std::fs::remove_dir_all(&temp_dir).ok();
}

#[test]
fn test_decent_sampler_export() {
    let sine_wave: Vec<f32> = (0..44100)
        .map(|i| (2.0 * std::f32::consts::PI * 440.0 * i as f32 / 44100.0).sin() * 0.5)
        .collect();

    // Create test samples
    let test_samples = vec![
        Sample {
            note: 64, // E4
            velocity: 64,
            audio_data: sine_wave.clone(),
            sample_rate: 44100,
            channels: 1,
            recorded_at: SystemTime::now(),
            midi_timing: Duration::from_millis(100),
            audio_timing: Duration::from_millis(2000),
        },
        Sample {
            note: 64, // E4
            velocity: 127,
            audio_data: sine_wave,
            sample_rate: 44100,
            channels: 1,
            recorded_at: SystemTime::now(),
            midi_timing: Duration::from_millis(100),
            audio_timing: Duration::from_millis(2000),
        },
    ];

    // Create temp directory for test
    let temp_dir = std::env::temp_dir().join("batcherbird_test_dspreset");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let config = ExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "TestInstrument_{note_name}_{note}_{velocity}.wav".to_string(),
        sample_format: AudioFormat::DecentSampler,
        normalize: false,
        fade_in_ms: 0.0,
        fade_out_ms: 0.0,
        apply_detection: true,
        detection_config: DetectionConfig::default(),
        creator_name: Some("Test User".to_string()),
        instrument_description: Some("Test Decent Sampler instrument".to_string()),
        embed_metadata: true,
    };

    let exporter = SampleExporter::new(config).unwrap();
    let files = exporter.export_samples(&test_samples).unwrap();

    // Should have 2 WAV files + 1 .dspreset file
    assert_eq!(files.len(), 3);

    // Find and verify .dspreset file
    let dspreset_file = files
        .iter()
        .find(|f| f.extension().is_some_and(|ext| ext == "dspreset"))
        .unwrap();
    let dspreset_content = std::fs::read_to_string(dspreset_file).unwrap();

    assert!(dspreset_content.contains("Generated by Batcherbird"));
    assert!(dspreset_content.contains("Test User"));
    assert!(dspreset_content.contains("<DecentSampler"));
    assert!(dspreset_content.contains("<group loVel="));
    assert!(dspreset_content.contains("<sample"));
    assert!(dspreset_content.contains("path="));
    assert!(dspreset_content.contains("loNote=\"64\""));
    assert!(dspreset_content.contains("loopEnabled=\"true\""));
    assert!(dspreset_content.contains("loopCrossfade="));

    // Cleanup
    std::fs::remove_dir_all(&temp_dir).ok();
}

#[test]
fn test_sfz_export_with_loop_crossfade() {
    let sine_wave: Vec<f32> = (0..44100)
        .map(|i| (2.0 * std::f32::consts::PI * 440.0 * i as f32 / 44100.0).sin() * 0.5)
        .collect();

    let test_samples = vec![Sample {
        note: 60,
        velocity: 100,
        audio_data: sine_wave,
        sample_rate: 44100,
        channels: 1,
        recorded_at: SystemTime::now(),
        midi_timing: Duration::from_millis(100),
        audio_timing: Duration::from_millis(2000),
    }];

    let temp_dir = std::env::temp_dir().join("batcherbird_test_sfz_loop");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let config = ExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "Test_{note_name}_{note}_{velocity}.wav".to_string(),
        sample_format: AudioFormat::SFZ,
        normalize: false,
        fade_in_ms: 0.0,
        fade_out_ms: 0.0,
        apply_detection: true,
        detection_config: DetectionConfig::default(),
        creator_name: Some("Test User".to_string()),
        instrument_description: Some("Test SFZ Loop instrument".to_string()),
        embed_metadata: true,
    };

    let exporter = SampleExporter::new(config).unwrap();
    let files = exporter.export_samples(&test_samples).unwrap();

    let sfz_file = files
        .iter()
        .find(|f| f.extension().is_some_and(|ext| ext == "sfz"))
        .unwrap();
    let sfz_content = std::fs::read_to_string(sfz_file).unwrap();

    assert!(sfz_content.contains("loop_mode=loop_continuous"));
    assert!(sfz_content.contains("loop_start="));
    assert!(sfz_content.contains("loop_end="));
    assert!(sfz_content.contains("loop_crossfade="));

    // Cleanup
    std::fs::remove_dir_all(&temp_dir).ok();
}

#[test]
fn test_riff_metadata_embedding_roundtrip() {
    let sine_wave: Vec<f32> = (0..44100)
        .map(|i| (2.0 * std::f32::consts::PI * 440.0 * i as f32 / 44100.0).sin() * 0.5)
        .collect();

    let sample = Sample {
        note: 69, // A4
        velocity: 110,
        audio_data: sine_wave,
        sample_rate: 44100,
        channels: 1,
        recorded_at: SystemTime::now(),
        midi_timing: Duration::from_millis(100),
        audio_timing: Duration::from_millis(1000),
    };

    let temp_dir = std::env::temp_dir().join("batcherbird_test_riff_metadata");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let config = ExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "Meta_{note_name}_{note}_{velocity}.wav".to_string(),
        sample_format: AudioFormat::Wav24Bit,
        normalize: false,
        fade_in_ms: 0.0,
        fade_out_ms: 0.0,
        apply_detection: true,
        detection_config: DetectionConfig::default(),
        creator_name: Some("Batcherbird Studio".to_string()),
        instrument_description: Some("Custom Prophet-5 Lead".to_string()),
        embed_metadata: true,
    };

    let exporter = SampleExporter::new(config).unwrap();
    let wav_path = exporter.export_sample(&sample).unwrap();

    // Verify file exists
    assert!(wav_path.exists());

    // Verify hound can read audio data without any corruption
    let mut reader = hound::WavReader::open(&wav_path).unwrap();
    let spec = reader.spec();
    assert_eq!(spec.sample_rate, 44100);
    assert_eq!(spec.channels, 1);
    assert_eq!(spec.bits_per_sample, 24);
    let sample_count = reader.samples::<i32>().count();
    assert_eq!(sample_count, 44100);

    // Read and verify RIFF chunk metadata
    let meta = read_wav_metadata(&wav_path).unwrap();

    // smpl chunk
    assert_eq!(meta.midi_unity_note, Some(69));
    assert_eq!(meta.sample_period_ns, Some(22676)); // 1_000_000_000 / 44100 = 22675.7 -> 22676
    assert!(meta.loop_points.is_some());

    // bext chunk
    assert_eq!(meta.bext_originator.as_deref(), Some("Batcherbird Studio"));
    assert_eq!(meta.bext_description.as_deref(), Some("Custom Prophet-5 Lead"));
    assert!(meta.bext_origination_date.is_some());
    assert!(meta.bext_origination_time.is_some());

    // INFO chunk
    assert_eq!(meta.info_title.as_deref(), Some("A4 (Note 69)"));
    assert_eq!(meta.info_artist.as_deref(), Some("Batcherbird Studio"));
    assert_eq!(meta.info_software.as_deref(), Some("Batcherbird"));
    assert!(meta.info_comment.unwrap().contains("Velocity: 110"));

    // Cleanup
    std::fs::remove_dir_all(&temp_dir).ok();
}

#[test]
fn test_simultaneous_ds_and_sfz_integration() {
    let sine_wave: Vec<f32> = (0..22050)
        .map(|i| (2.0 * std::f32::consts::PI * 440.0 * i as f32 / 44100.0).sin() * 0.5)
        .collect();

    let sample = Sample {
        note: 60,
        velocity: 100,
        audio_data: sine_wave,
        sample_rate: 44100,
        channels: 1,
        recorded_at: SystemTime::now(),
        midi_timing: Duration::from_millis(50),
        audio_timing: Duration::from_millis(500),
    };

    let temp_dir = std::env::temp_dir().join("batcherbird_test_simul_integration");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let config = ExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "Patch_{note_name}_{note}_{velocity}.wav".to_string(),
        sample_format: AudioFormat::DecentSamplerAndSfz,
        normalize: false,
        fade_in_ms: 0.0,
        fade_out_ms: 0.0,
        apply_detection: false,
        detection_config: DetectionConfig::default(),
        creator_name: Some("Sound Designer".to_string()),
        instrument_description: Some("Hybrid Pad".to_string()),
        embed_metadata: true,
    };

    let exporter = SampleExporter::new(config).unwrap();
    let exported = exporter.export_samples(&[sample]).unwrap();

    // 1 WAV file + 1 .dspreset + 1 .sfz = 3 files
    assert_eq!(exported.len(), 3);

    let dspreset_path = temp_dir.join("Patch.dspreset");
    let sfz_path = temp_dir.join("Patch.sfz");
    let wav_path = temp_dir.join("Patch_C4_60_vel100.wav");

    assert!(dspreset_path.exists());
    assert!(sfz_path.exists());
    assert!(wav_path.exists());

    // Both presets should reference the exact same relative WAV filename
    let ds_xml = std::fs::read_to_string(&dspreset_path).unwrap();
    let sfz_txt = std::fs::read_to_string(&sfz_path).unwrap();

    assert!(ds_xml.contains("Patch_C4_60_vel100.wav"));
    assert!(sfz_txt.contains("Patch_C4_60_vel100.wav"));

    std::fs::remove_dir_all(&temp_dir).ok();
}

#[test]
fn test_batch_exporter_pipeline_integration() {
    let sample = Sample {
        note: 72,
        velocity: 120,
        audio_data: vec![0.1; 1000],
        sample_rate: 44100,
        channels: 1,
        recorded_at: SystemTime::now(),
        midi_timing: Duration::from_millis(50),
        audio_timing: Duration::from_millis(500),
    };

    let temp_dir = std::env::temp_dir().join("batcherbird_test_batch_pipeline");
    std::fs::create_dir_all(&temp_dir).unwrap();

    let batch_cfg = BatchExportConfig {
        output_directory: temp_dir.clone(),
        naming_pattern: "Test_{note_name}_{note}_{velocity}.wav".to_string(),
        formats: vec![AudioFormat::DecentSampler, AudioFormat::SFZ, AudioFormat::Wav16Bit],
        organize_subdirectories: true,
        ..Default::default()
    };

    let batch_exp = BatchExporter::new(batch_cfg).unwrap();
    let res = batch_exp.export_samples(&[sample]).unwrap();

    assert_eq!(res.files_by_format.len(), 3);
    assert!(temp_dir.join("DecentSampler/Test.dspreset").exists());
    assert!(temp_dir.join("SFZ/Test.sfz").exists());
    assert!(temp_dir.join("WAV_16Bit/Test_C5_72_vel120.wav").exists());

    std::fs::remove_dir_all(&temp_dir).ok();
}


